//! Single source of truth for command metadata.
//!
//! The [`COMMAND_TABLE`] is a static slice of [`CommandSpec`] entries
//! describing every command we support. It powers:
//!
//! - `COMMAND COUNT / DOCS / INFO / LIST` (admin commands clients use to
//!   probe what we support).
//! - `metric_label_for_command()` (bounded-cardinality metric label
//!   whitelist — replaces the hand-rolled match in `connection.rs`).
//! - `is_known_command()` (used by MULTI to decide whether to set the
//!   `EXECABORT` flag).
//! - Future use by `CLUSTER COUNTKEYSINSLOT`-style commands.
//!
//! Adding a new command means adding one row here and one branch in
//! `dispatch()` — the registry guarantees the metric label and
//! command-info responses stay in sync without manual upkeep.

use bytes::Bytes;

use crate::protocol::types::RespValue;

/// Per-command specification. Mirrors the fields Redis exposes via
/// `COMMAND INFO` / `COMMAND DOCS` so client libraries can introspect.
#[derive(Debug, Clone, Copy)]
pub struct CommandSpec {
    /// Uppercase command name (matches the dispatch table).
    pub name: &'static str,
    /// Number of arguments (including the command name itself).
    /// Negative means "at least |arity|" (matching Redis convention).
    pub arity: i32,
    /// Command flags (e.g. "write", "readonly", "fast"). Comma-separated.
    pub flags: &'static [&'static str],
    /// 1-based position of the first key in argv, or 0 if no keys.
    pub first_key: i32,
    /// 1-based position of the last key in argv, or -N to mean "Nth from end".
    pub last_key: i32,
    /// Step between successive keys (1 for SET, 2 for MSET).
    pub key_step: i32,
    /// ACL categories (e.g. "@read", "@write", "@fast"). Comma-separated.
    pub acl_categories: &'static [&'static str],
    /// One-line summary used by `COMMAND DOCS`.
    pub summary: &'static str,
    /// Group ("string", "hash", "set", etc.) used by `COMMAND DOCS`.
    pub group: &'static str,
    /// Version when the command was first introduced — informational.
    pub since: &'static str,
}

/// Master command table. Order doesn't matter; commands are looked up by
/// case-insensitive name.
///
/// Keep this in sync with `dispatch()` in `commands/mod.rs`. The unit
/// test at the bottom of this module asserts every dispatched command
/// has a registry entry.
pub static COMMAND_TABLE: &[CommandSpec] = &[
    // ---- Connection / server ----
    spec(
        "PING",
        -1,
        &["fast", "loading", "stale"],
        0,
        0,
        0,
        "Returns the server's liveness response.",
        "connection",
        "1.0.0",
    ),
    spec(
        "ECHO",
        2,
        &["fast", "loading", "stale"],
        0,
        0,
        0,
        "Returns the given string.",
        "connection",
        "1.0.0",
    ),
    spec(
        "HELLO",
        -1,
        &["no-auth", "fast", "loading", "stale"],
        0,
        0,
        0,
        "Handshakes with the Redis server.",
        "connection",
        "6.0.0",
    ),
    spec(
        "QUIT",
        1,
        &["loading", "stale", "fast", "no-auth"],
        0,
        0,
        0,
        "Closes the connection.",
        "connection",
        "1.0.0",
    ),
    spec(
        "RESET",
        1,
        &["no-auth", "loading", "stale", "fast"],
        0,
        0,
        0,
        "Resets the connection.",
        "connection",
        "6.2.0",
    ),
    spec(
        "AUTH",
        -2,
        &["no-auth", "fast", "loading", "stale"],
        0,
        0,
        0,
        "Authenticates the connection.",
        "connection",
        "1.0.0",
    ),
    spec(
        "SELECT",
        2,
        &["loading", "stale", "fast"],
        0,
        0,
        0,
        "Selects the active database.",
        "connection",
        "1.0.0",
    ),
    // ---- Server admin ----
    spec(
        "CLIENT",
        -2,
        &["admin", "loading", "stale"],
        0,
        0,
        0,
        "A container for client-management subcommands.",
        "server",
        "2.4.0",
    ),
    spec(
        "COMMAND",
        -1,
        &["loading", "stale"],
        0,
        0,
        0,
        "A container for command introspection.",
        "server",
        "2.8.13",
    ),
    spec(
        "INFO",
        -1,
        &["loading", "stale"],
        0,
        0,
        0,
        "Returns information and statistics about the server.",
        "server",
        "1.0.0",
    ),
    spec(
        "CONFIG",
        -2,
        &["admin", "loading", "stale"],
        0,
        0,
        0,
        "A container for runtime config commands.",
        "server",
        "2.0.0",
    ),
    spec(
        "DBSIZE",
        1,
        &["readonly", "fast"],
        0,
        0,
        0,
        "Returns the number of keys in the current db.",
        "server",
        "1.0.0",
    ),
    spec(
        "TIME",
        1,
        &["loading", "stale", "fast"],
        0,
        0,
        0,
        "Returns the server time.",
        "server",
        "2.6.0",
    ),
    spec(
        "RANDOMKEY",
        1,
        &["readonly"],
        0,
        0,
        0,
        "Returns a random key.",
        "server",
        "1.0.0",
    ),
    spec(
        "KEYS",
        2,
        &["readonly", "slow"],
        0,
        0,
        0,
        "Returns all keys matching a pattern.",
        "server",
        "1.0.0",
    ),
    spec(
        "FLUSHDB",
        -1,
        &["write", "slow"],
        0,
        0,
        0,
        "Removes all keys in the current db.",
        "server",
        "1.0.0",
    ),
    spec(
        "FLUSHALL",
        -1,
        &["write", "slow"],
        0,
        0,
        0,
        "Removes all keys from all databases.",
        "server",
        "1.0.0",
    ),
    spec(
        "SHUTDOWN",
        -1,
        &["admin", "loading", "stale", "no-multi"],
        0,
        0,
        0,
        "Synchronously shuts down the server.",
        "server",
        "1.0.0",
    ),
    spec(
        "BGSAVE",
        -1,
        &["admin"],
        0,
        0,
        0,
        "Asynchronously saves the database to disk.",
        "server",
        "1.0.0",
    ),
    spec(
        "SAVE",
        1,
        &["admin", "no-async-loading", "no-multi"],
        0,
        0,
        0,
        "Synchronously saves the database to disk.",
        "server",
        "1.0.0",
    ),
    spec(
        "BGREWRITEAOF",
        1,
        &["admin"],
        0,
        0,
        0,
        "Asynchronously rewrites the AOF.",
        "server",
        "1.0.0",
    ),
    spec(
        "LASTSAVE",
        1,
        &["loading", "stale", "fast"],
        0,
        0,
        0,
        "Returns the unix time of the last successful save.",
        "server",
        "1.0.0",
    ),
    spec(
        "WAIT",
        3,
        &["no-script"],
        0,
        0,
        0,
        "Blocks until N replicas have acknowledged.",
        "server",
        "3.0.0",
    ),
    spec(
        "DEBUG",
        -2,
        &["admin", "no-script", "loading"],
        0,
        0,
        0,
        "A container for debugging subcommands.",
        "server",
        "1.0.0",
    ),
    spec(
        "SLOWLOG",
        -2,
        &["admin", "loading", "stale"],
        0,
        0,
        0,
        "A container for slow-log commands.",
        "server",
        "2.2.12",
    ),
    spec(
        "MEMORY",
        -2,
        &["loading", "stale"],
        0,
        0,
        0,
        "A container for memory diagnostics.",
        "server",
        "4.0.0",
    ),
    spec(
        "LATENCY",
        -2,
        &["admin", "loading", "stale"],
        0,
        0,
        0,
        "A container for latency diagnostics.",
        "server",
        "2.8.13",
    ),
    spec(
        "OBJECT",
        -2,
        &["readonly"],
        0,
        0,
        0,
        "A container for object introspection.",
        "generic",
        "2.2.3",
    ),
    spec(
        "ACL",
        -2,
        &["admin", "no-script", "loading", "stale"],
        0,
        0,
        0,
        "A container for ACL management.",
        "server",
        "6.0.0",
    ),
    // ---- Strings ----
    spec(
        "GET",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the string value of a key.",
        "string",
        "1.0.0",
    ),
    spec(
        "SET",
        -3,
        &["write", "denyoom"],
        1,
        1,
        1,
        "Sets the string value of a key.",
        "string",
        "1.0.0",
    ),
    spec(
        "DEL",
        -2,
        &["write"],
        1,
        -1,
        1,
        "Removes the specified keys.",
        "generic",
        "1.0.0",
    ),
    spec(
        "EXISTS",
        -2,
        &["readonly", "fast"],
        1,
        -1,
        1,
        "Determines whether keys exist.",
        "generic",
        "1.0.0",
    ),
    spec(
        "SETNX",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Sets the value of a key if it doesn't exist.",
        "string",
        "1.0.0",
    ),
    spec(
        "SETEX",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "Sets a key with a TTL in seconds.",
        "string",
        "2.0.0",
    ),
    spec(
        "PSETEX",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "Sets a key with a TTL in milliseconds.",
        "string",
        "2.6.0",
    ),
    spec(
        "GETDEL",
        2,
        &["write", "fast"],
        1,
        1,
        1,
        "Returns and deletes the value of a key.",
        "string",
        "6.2.0",
    ),
    spec(
        "MGET",
        -2,
        &["readonly", "fast"],
        1,
        -1,
        1,
        "Returns multiple values.",
        "string",
        "1.0.0",
    ),
    spec(
        "MSET",
        -3,
        &["write", "denyoom"],
        1,
        -1,
        2,
        "Atomically sets multiple keys.",
        "string",
        "1.0.1",
    ),
    spec(
        "INCR",
        2,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Increments an integer value by 1.",
        "string",
        "1.0.0",
    ),
    spec(
        "DECR",
        2,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Decrements an integer value by 1.",
        "string",
        "1.0.0",
    ),
    spec(
        "INCRBY",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Increments an integer value.",
        "string",
        "1.0.0",
    ),
    spec(
        "DECRBY",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Decrements an integer value.",
        "string",
        "1.0.0",
    ),
    spec(
        "INCRBYFLOAT",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Increments a float value.",
        "string",
        "2.6.0",
    ),
    spec(
        "APPEND",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Appends to a string value.",
        "string",
        "2.0.0",
    ),
    spec(
        "STRLEN",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the length of a string.",
        "string",
        "2.2.0",
    ),
    spec(
        "GETRANGE",
        4,
        &["readonly"],
        1,
        1,
        1,
        "Returns a substring.",
        "string",
        "2.4.0",
    ),
    spec(
        "SETRANGE",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "Overwrites a substring.",
        "string",
        "2.2.0",
    ),
    // ---- Generic / TTL ----
    spec(
        "TTL",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "TTL in seconds.",
        "generic",
        "1.0.0",
    ),
    spec(
        "PTTL",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "TTL in milliseconds.",
        "generic",
        "2.6.0",
    ),
    spec(
        "EXPIRETIME",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Absolute expire time in seconds.",
        "generic",
        "7.0.0",
    ),
    spec(
        "PEXPIRETIME",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Absolute expire time in milliseconds.",
        "generic",
        "7.0.0",
    ),
    spec(
        "EXPIRE",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "Sets the expiration in seconds.",
        "generic",
        "1.0.0",
    ),
    spec(
        "PEXPIRE",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "Sets the expiration in milliseconds.",
        "generic",
        "2.6.0",
    ),
    spec(
        "EXPIREAT",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "Sets the absolute expiration in seconds.",
        "generic",
        "1.2.0",
    ),
    spec(
        "PEXPIREAT",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "Sets the absolute expiration in milliseconds.",
        "generic",
        "2.6.0",
    ),
    spec(
        "PERSIST",
        2,
        &["write", "fast"],
        1,
        1,
        1,
        "Removes the expiration.",
        "generic",
        "2.2.0",
    ),
    spec(
        "TYPE",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the type of a key.",
        "generic",
        "1.0.0",
    ),
    spec(
        "UNLINK",
        -2,
        &["write", "fast"],
        1,
        -1,
        1,
        "Asynchronously deletes keys.",
        "generic",
        "4.0.0",
    ),
    spec(
        "TOUCH",
        -2,
        &["readonly", "fast"],
        1,
        -1,
        1,
        "Updates the last access time.",
        "generic",
        "3.2.1",
    ),
    spec("RENAME", 3, &["write"], 1, 2, 1, "Renames a key.", "generic", "1.0.0"),
    spec(
        "RENAMENX",
        3,
        &["write", "fast"],
        1,
        2,
        1,
        "Renames a key if the destination doesn't exist.",
        "generic",
        "1.0.0",
    ),
    // ---- Transactions ----
    spec(
        "MULTI",
        1,
        &["no-script", "loading", "stale", "fast"],
        0,
        0,
        0,
        "Starts a transaction.",
        "transactions",
        "1.2.0",
    ),
    spec(
        "EXEC",
        1,
        &["no-script", "loading", "stale"],
        0,
        0,
        0,
        "Executes the queued commands.",
        "transactions",
        "1.2.0",
    ),
    spec(
        "DISCARD",
        1,
        &["no-script", "loading", "stale", "fast"],
        0,
        0,
        0,
        "Discards the queued commands.",
        "transactions",
        "2.0.0",
    ),
    spec(
        "WATCH",
        -2,
        &["no-script", "loading", "stale", "fast"],
        1,
        -1,
        1,
        "Marks keys for conditional execution.",
        "transactions",
        "2.2.0",
    ),
    spec(
        "UNWATCH",
        1,
        &["no-script", "loading", "stale", "fast"],
        0,
        0,
        0,
        "Forgets watched keys.",
        "transactions",
        "2.2.0",
    ),
    // ---- Hashes ----
    spec(
        "HSET",
        -4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Sets a field-value pair.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HGET",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns a field value.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HDEL",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "Deletes fields.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HEXISTS",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Tests for field existence.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HLEN",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the number of fields.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HGETALL",
        2,
        &["readonly"],
        1,
        1,
        1,
        "Returns all field-value pairs.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HKEYS",
        2,
        &["readonly"],
        1,
        1,
        1,
        "Returns all field names.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HVALS",
        2,
        &["readonly"],
        1,
        1,
        1,
        "Returns all values.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HMGET",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns multiple field values.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HMSET",
        -4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Sets multiple field values.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HINCRBY",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Increments a field value.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HINCRBYFLOAT",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Increments a float field value.",
        "hash",
        "2.6.0",
    ),
    spec(
        "HSETNX",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Sets a field if it doesn't exist.",
        "hash",
        "2.0.0",
    ),
    spec(
        "HSTRLEN",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the length of a field value.",
        "hash",
        "3.2.0",
    ),
    spec(
        "HRANDFIELD",
        -2,
        &["readonly"],
        1,
        1,
        1,
        "Returns one or more random fields.",
        "hash",
        "6.2.0",
    ),
    // ---- Sets ----
    spec(
        "SADD",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Adds members to a set.",
        "set",
        "1.0.0",
    ),
    spec(
        "SREM",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "Removes members from a set.",
        "set",
        "1.0.0",
    ),
    spec(
        "SISMEMBER",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Tests for set membership.",
        "set",
        "1.0.0",
    ),
    spec(
        "SMISMEMBER",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Tests multiple members.",
        "set",
        "6.2.0",
    ),
    spec(
        "SCARD",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the cardinality.",
        "set",
        "1.0.0",
    ),
    spec(
        "SMEMBERS",
        2,
        &["readonly"],
        1,
        1,
        1,
        "Returns all members.",
        "set",
        "1.0.0",
    ),
    spec(
        "SPOP",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "Removes and returns members.",
        "set",
        "1.0.0",
    ),
    spec(
        "SRANDMEMBER",
        -2,
        &["readonly"],
        1,
        1,
        1,
        "Returns random members.",
        "set",
        "1.0.0",
    ),
    spec(
        "SMOVE",
        4,
        &["write", "fast"],
        1,
        2,
        1,
        "Moves a member between sets.",
        "set",
        "1.0.0",
    ),
    spec(
        "SINTER",
        -2,
        &["readonly", "slow"],
        1,
        -1,
        1,
        "Returns the intersection.",
        "set",
        "1.0.0",
    ),
    spec(
        "SUNION",
        -2,
        &["readonly", "slow"],
        1,
        -1,
        1,
        "Returns the union.",
        "set",
        "1.0.0",
    ),
    spec(
        "SDIFF",
        -2,
        &["readonly", "slow"],
        1,
        -1,
        1,
        "Returns the difference.",
        "set",
        "1.0.0",
    ),
    spec(
        "SINTERSTORE",
        -3,
        &["write", "denyoom", "slow"],
        1,
        -1,
        1,
        "Stores the intersection.",
        "set",
        "1.0.0",
    ),
    spec(
        "SUNIONSTORE",
        -3,
        &["write", "denyoom", "slow"],
        1,
        -1,
        1,
        "Stores the union.",
        "set",
        "1.0.0",
    ),
    spec(
        "SDIFFSTORE",
        -3,
        &["write", "denyoom", "slow"],
        1,
        -1,
        1,
        "Stores the difference.",
        "set",
        "1.0.0",
    ),
    spec(
        "SINTERCARD",
        -3,
        &["readonly", "slow"],
        0,
        0,
        0,
        "Returns intersection cardinality.",
        "set",
        "7.0.0",
    ),
    // ---- Lists ----
    spec(
        "LPUSH",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Prepends elements to a list.",
        "list",
        "1.0.0",
    ),
    spec(
        "RPUSH",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Appends elements to a list.",
        "list",
        "1.0.0",
    ),
    spec(
        "LPUSHX",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Prepends if key exists.",
        "list",
        "2.2.0",
    ),
    spec(
        "RPUSHX",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Appends if key exists.",
        "list",
        "2.2.0",
    ),
    spec(
        "LPOP",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "Pops elements from the head.",
        "list",
        "1.0.0",
    ),
    spec(
        "RPOP",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "Pops elements from the tail.",
        "list",
        "1.0.0",
    ),
    spec(
        "LLEN",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the list length.",
        "list",
        "1.0.0",
    ),
    spec(
        "LINDEX",
        3,
        &["readonly"],
        1,
        1,
        1,
        "Returns an element by index.",
        "list",
        "1.0.0",
    ),
    spec(
        "LRANGE",
        4,
        &["readonly"],
        1,
        1,
        1,
        "Returns elements in a range.",
        "list",
        "1.0.0",
    ),
    spec(
        "LSET",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "Sets an element by index.",
        "list",
        "1.0.0",
    ),
    spec("LTRIM", 4, &["write"], 1, 1, 1, "Trims a list.", "list", "1.0.0"),
    spec("LREM", 4, &["write"], 1, 1, 1, "Removes elements.", "list", "1.0.0"),
    spec(
        "LINSERT",
        5,
        &["write", "denyoom"],
        1,
        1,
        1,
        "Inserts an element.",
        "list",
        "2.2.0",
    ),
    spec(
        "LPOS",
        -3,
        &["readonly"],
        1,
        1,
        1,
        "Returns the position of an element.",
        "list",
        "6.0.6",
    ),
    spec(
        "LMOVE",
        5,
        &["write", "denyoom"],
        1,
        2,
        1,
        "Atomically moves an element.",
        "list",
        "6.2.0",
    ),
    spec(
        "LMPOP",
        -4,
        &["write", "slow"],
        0,
        0,
        0,
        "Pops from the first non-empty list.",
        "list",
        "7.0.0",
    ),
    // ---- Sorted Sets ----
    spec(
        "ZADD",
        -4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Adds members to a sorted set.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZCARD",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the cardinality.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZSCORE",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the score of a member.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZREM",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "Removes members.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZRANK",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the index of a member.",
        "sorted-set",
        "2.0.0",
    ),
    spec(
        "ZREVRANK",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns the reverse index.",
        "sorted-set",
        "2.0.0",
    ),
    spec(
        "ZINCRBY",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "Increments a score.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZRANGE",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "Returns members in a range.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZREVRANGE",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "Returns members in reverse range.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZCOUNT",
        4,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Counts members in a score range.",
        "sorted-set",
        "2.0.0",
    ),
    spec(
        "ZLEXCOUNT",
        4,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Counts members in a lex range.",
        "sorted-set",
        "2.8.9",
    ),
    spec(
        "ZRANGEBYSCORE",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "Range by score.",
        "sorted-set",
        "1.0.5",
    ),
    spec(
        "ZRANGEBYLEX",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "Range by lex.",
        "sorted-set",
        "2.8.9",
    ),
    spec(
        "ZREMRANGEBYRANK",
        4,
        &["write"],
        1,
        1,
        1,
        "Removes by rank.",
        "sorted-set",
        "2.0.0",
    ),
    spec(
        "ZREMRANGEBYSCORE",
        4,
        &["write"],
        1,
        1,
        1,
        "Removes by score.",
        "sorted-set",
        "1.2.0",
    ),
    spec(
        "ZREMRANGEBYLEX",
        4,
        &["write"],
        1,
        1,
        1,
        "Removes by lex.",
        "sorted-set",
        "2.8.9",
    ),
    spec(
        "ZPOPMIN",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "Pops the lowest-scoring member.",
        "sorted-set",
        "5.0.0",
    ),
    spec(
        "ZPOPMAX",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "Pops the highest-scoring member.",
        "sorted-set",
        "5.0.0",
    ),
    spec(
        "ZRANDMEMBER",
        -2,
        &["readonly"],
        1,
        1,
        1,
        "Returns random members.",
        "sorted-set",
        "6.2.0",
    ),
    spec(
        "ZMSCORE",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "Returns scores for multiple members.",
        "sorted-set",
        "6.2.0",
    ),
    // ---- Pub/Sub ----
    spec(
        "SUBSCRIBE",
        -2,
        &["pubsub", "loading", "stale"],
        0,
        0,
        0,
        "Subscribes to channels.",
        "pubsub",
        "2.0.0",
    ),
    spec(
        "UNSUBSCRIBE",
        -1,
        &["pubsub", "loading", "stale"],
        0,
        0,
        0,
        "Unsubscribes from channels.",
        "pubsub",
        "2.0.0",
    ),
    spec(
        "PSUBSCRIBE",
        -2,
        &["pubsub", "loading", "stale"],
        0,
        0,
        0,
        "Subscribes to patterns.",
        "pubsub",
        "2.0.0",
    ),
    spec(
        "PUNSUBSCRIBE",
        -1,
        &["pubsub", "loading", "stale"],
        0,
        0,
        0,
        "Unsubscribes from patterns.",
        "pubsub",
        "2.0.0",
    ),
    spec(
        "PUBLISH",
        3,
        &["pubsub", "loading", "stale", "fast"],
        0,
        0,
        0,
        "Publishes a message.",
        "pubsub",
        "2.0.0",
    ),
    spec(
        "PUBSUB",
        -2,
        &["pubsub", "loading", "stale"],
        0,
        0,
        0,
        "Pub/sub introspection.",
        "pubsub",
        "2.8.0",
    ),
];

/// const-fn constructor so the table is purely static data — no init cost.
#[allow(clippy::too_many_arguments)]
const fn spec(
    name: &'static str,
    arity: i32,
    flags: &'static [&'static str],
    first_key: i32,
    last_key: i32,
    key_step: i32,
    summary: &'static str,
    group: &'static str,
    since: &'static str,
) -> CommandSpec {
    CommandSpec {
        name,
        arity,
        flags,
        first_key,
        last_key,
        key_step,
        acl_categories: &[], // populated at runtime if we ever need to derive
        summary,
        group,
        since,
    }
}

/// Look up a spec by case-insensitive name.
pub fn lookup(name: &[u8]) -> Option<&'static CommandSpec> {
    // Linear scan: ~150 entries × ~10 ASCII compares = ~1500 cycles, well
    // below FDB latency. A perfect hash isn't worth the build complexity.
    let upper = name.to_ascii_uppercase();
    COMMAND_TABLE.iter().find(|s| s.name.as_bytes() == upper.as_slice())
}

/// True if `name` is a recognized command.
pub fn is_known(name: &[u8]) -> bool {
    lookup(name).is_some()
}

/// Total number of registered commands.
pub fn count() -> usize {
    COMMAND_TABLE.len()
}

/// Static metric label for `name`. Falls back to `"UNKNOWN"` so an
/// attacker can't blow up label cardinality with random command names.
///
/// Returns a `&'static str` so it can be passed to `with_label_values`
/// without allocation on the hot path.
pub fn metric_label(name: &[u8]) -> &'static str {
    match lookup(name) {
        Some(s) => s.name,
        None => "UNKNOWN",
    }
}

/// Render a `CommandSpec` as the RESP array Redis returns from
/// `COMMAND INFO`. Format:
///
/// 1. name (bulk string, lowercase)
/// 2. arity (integer)
/// 3. flags (array of simple strings)
/// 4. first key position (integer)
/// 5. last key position (integer)
/// 6. step (integer)
/// 7. ACL categories (array of simple strings, empty here)
/// 8. tips (array, empty)
/// 9. key specs (array, empty)
/// 10. subcommands (array, empty)
pub fn render_command_info(spec: &CommandSpec) -> RespValue {
    let flags: Vec<RespValue> = spec
        .flags
        .iter()
        .map(|f| RespValue::SimpleString(Bytes::from(*f)))
        .collect();
    let acl: Vec<RespValue> = spec
        .acl_categories
        .iter()
        .map(|f| RespValue::SimpleString(Bytes::from(*f)))
        .collect();
    RespValue::Array(Some(vec![
        RespValue::BulkString(Some(Bytes::from(spec.name.to_ascii_lowercase()))),
        RespValue::Integer(spec.arity as i64),
        RespValue::Array(Some(flags)),
        RespValue::Integer(spec.first_key as i64),
        RespValue::Integer(spec.last_key as i64),
        RespValue::Integer(spec.key_step as i64),
        RespValue::Array(Some(acl)),
        RespValue::Array(Some(vec![])),
        RespValue::Array(Some(vec![])),
        RespValue::Array(Some(vec![])),
    ]))
}

/// Render a `CommandSpec` as the RESP map returned by `COMMAND DOCS`.
pub fn render_command_docs(spec: &CommandSpec) -> RespValue {
    RespValue::Map(vec![
        (
            RespValue::BulkString(Some(Bytes::from_static(b"summary"))),
            RespValue::BulkString(Some(Bytes::from(spec.summary))),
        ),
        (
            RespValue::BulkString(Some(Bytes::from_static(b"since"))),
            RespValue::BulkString(Some(Bytes::from(spec.since))),
        ),
        (
            RespValue::BulkString(Some(Bytes::from_static(b"group"))),
            RespValue::BulkString(Some(Bytes::from(spec.group))),
        ),
        (
            RespValue::BulkString(Some(Bytes::from_static(b"arguments"))),
            RespValue::Array(Some(vec![])),
        ),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lookup_is_case_insensitive() {
        assert!(lookup(b"PING").is_some());
        assert!(lookup(b"ping").is_some());
        assert!(lookup(b"PiNg").is_some());
        assert!(lookup(b"NOTACOMMAND").is_none());
    }

    #[test]
    fn metric_label_unknown_falls_back_to_static() {
        let l = metric_label(b"definitely_not_a_command");
        assert_eq!(l, "UNKNOWN");
    }

    #[test]
    fn count_matches_table_len() {
        assert_eq!(count(), COMMAND_TABLE.len());
        assert!(count() > 100);
    }

    #[test]
    fn no_duplicate_names() {
        // Two duplicate registry entries would silently make
        // is_known/lookup ambiguous. Catch it at compile/test time.
        let mut names: Vec<&'static str> = COMMAND_TABLE.iter().map(|s| s.name).collect();
        names.sort_unstable();
        for w in names.windows(2) {
            assert_ne!(w[0], w[1], "duplicate command in registry: {}", w[0]);
        }
    }

    #[test]
    fn names_are_uppercase() {
        for s in COMMAND_TABLE {
            assert_eq!(
                s.name,
                s.name.to_ascii_uppercase(),
                "command names in the registry must be uppercase"
            );
        }
    }
}
